name ='hono-react-router'
workers_dev = true
compatibility_date = "2024-11-18"
compatibility_flags = ["nodejs_compat"]
main = "./worker.ts"
assets = { directory = "./build/client/" }
preview_urls = true



[[d1_databases]]
binding = "DB"
database_name = "vendula-bags-db"
database_id = "47e3b618-2d95-47a6-9a4b-16f6d9197d86"
migrations_dir = "database/drizzle/migrations"
remote = true

[[r2_buckets]]
binding = "R2"
bucket_name = "vendula-design-images"
remote = true

[observability.logs]
enabled = true

[vars]
DEV = "true"
BETTER_AUTH_URL = "http://localhost:5173"
PUBLIC_IMAGE_BASE_URL = "https://img.vendulette.com"

 
[[services]]
binding = "IMAGE_WORKER"
service = "image-migration-worker"