-- CREATE TABLE IF NOT EXISTS users (
--     id INTEGER PRIMARY KEY AUTOINCREMENT,
--     email TEXT NOT NULL UNIQUE,
--     password_hash TEXT NOT NULL,
--     name TEXT,
--     is_admin INTEGER NOT NULL DEFAULT 1,
--     created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
--     updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
-- );

-- CREATE UNIQUE INDEX IF NOT EXISTS users_email_unique
-- ON users (email);